---- Base app schema

-- User
CREATE TABLE "user"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY (start with 1000) PRIMARY KEY,
    username varchar(128) NOT NULL UNIQUE,

    -- Auth
    pwd varchar(256),
    pwd_salt uuid NOT NUll DEFAULT  gen_random_uuid(),
    token_salt uuid NOT NUll DEFAULT  gen_random_uuid()

);


-- Task
CREATE TABLE TASK
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY (start with 1000) PRIMARY KEY,
    title varchar(256) NOT NULL
);

