# Cargo config file
# See: https://doc.rust-lang.org/cargo/reference/config.toml

# Environments variables set for all `cargo ...` commands.
[env]

# Scope down tracing, to filter out external lib tracing.
RUST_LOG="web_service_axum=debug"

# -- Service Environment Variables
#  IMPOTANT
#    For cargo commands only.
#    For deployed env, should be managed by container
#    (e.g. Kubernates).

## -- Secrets
# Keys and passwords below are for localhost dev ONLY.
# e.g., "welcome" type of passwords.
# i.e., Encryption not needed.

SERVICE_DB_URL="postgres://app_user:dev_only_pwd@localhost/app_db"

SERVICE_PWD_KEY = "vlgx5ZG9cycxs9WESjU8pWDxwcDtPGvv40NITmvXCYaYFVnkSTkj0JVMeBebZIq4QO2PqV3ybZwCBCA1NalCew"

SERVICE_TOKEN_KEY = "JpTeRpndMMohQk5-nBUBhmWTs53MnaeRk7TAAqy2sFEbpPV-0Mu6l9x7sZ2GSNwPt1Mst1rw9z0EsM3rHahpnw"
SERVICE_TOKEN_DURATION_SEC = "1800" # 30 minutes

# ..._KEY = base_64(base_64u(...))

## -- ConfigMap

# This will be relative to Cargo.toml
# In deployed images, probably use absolute path.
SERVICE_WEB_FOLDER="web-folder/"



